-- drop objects
drop table assignees cascade constraints;
drop table todos cascade constraints;

-- create tables
create table assignees (
    id                             number generated by default on null as identity  
                                   constraint assignees_id_pk primary key,
    full_name                      varchar2(255) not null,
    email                          varchar2(255),
    phone_number                   number,
    created                        date not null,
    created_by                     varchar2(255) not null,
    updated                        date not null,
    updated_by                     varchar2(255) not null
)
;

create table todos (
    id                             number generated by default on null as identity  
                                   constraint todos_id_pk primary key,
    assignee_id                    number
                                   constraint todos_assignee_id_fk
                                   references assignees on delete cascade,
    name                           varchar2(255) not null,
    due_date                       date,
    priority                       varchar2(50) constraint todos_priority_cc
                                   check (priority in ('P1','P2','P3')),
    status                         varchar2(50) constraint todos_status_cc
                                   check (status in ('OPEN','COMPLETE','ON HOLD','CANCELLED')),
    created                        date not null,
    created_by                     varchar2(255) not null,
    updated                        date not null,
    updated_by                     varchar2(255) not null
)
;


-- triggers
create or replace trigger assignees_biu
    before insert or update 
    on assignees
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := nvl(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := nvl(sys_context('APEX$SESSION','APP_USER'),user);
end assignees_biu;
/

create or replace trigger todos_biu
    before insert or update 
    on todos
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := nvl(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := nvl(sys_context('APEX$SESSION','APP_USER'),user);
end todos_biu;
/


-- indexes
create index todos_i1 on todos (assignee_id);
-- load data
 
insert into assignees (
    id,
    full_name,
    email,
    phone_number
) values (
    1,
    'Gricelda Luebbers',
    'gricelda.luebbers@aaab.com',
    26
);

insert into assignees (
    id,
    full_name,
    email,
    phone_number
) values (
    2,
    'Dean Bollich',
    'dean.bollich@aaac.com',
    58
);

insert into assignees (
    id,
    full_name,
    email,
    phone_number
) values (
    3,
    'Milo Manoni',
    'milo.manoni@aaad.com',
    8
);

insert into assignees (
    id,
    full_name,
    email,
    phone_number
) values (
    4,
    'Laurice Karl',
    'laurice.karl@aaae.com',
    9
);

insert into assignees (
    id,
    full_name,
    email,
    phone_number
) values (
    5,
    'August Rupel',
    'august.rupel@aaaf.com',
    36
);

insert into assignees (
    id,
    full_name,
    email,
    phone_number
) values (
    6,
    'Salome Guisti',
    'salome.guisti@aaag.com',
    19
);

insert into assignees (
    id,
    full_name,
    email,
    phone_number
) values (
    7,
    'Lovie Ritacco',
    'lovie.ritacco@aaah.com',
    36
);

insert into assignees (
    id,
    full_name,
    email,
    phone_number
) values (
    8,
    'Chaya Greczkowski',
    'chaya.greczkowski@aaai.com',
    51
);

insert into assignees (
    id,
    full_name,
    email,
    phone_number
) values (
    9,
    'Twila Coolbeth',
    'twila.coolbeth@aaaj.com',
    53
);

insert into assignees (
    id,
    full_name,
    email,
    phone_number
) values (
    10,
    'Carlotta Achenbach',
    'carlotta.achenbach@aaak.com',
    46
);

commit;
-- load data
-- load data
 
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    1,
    6,
    'NAS Device Upgrade',
    sysdate - 65,
    'P1',
    'OPEN'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    2,
    3,
    'Albert AI System',
    sysdate - 46,
    'P2',
    'COMPLETE'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    3,
    5,
    'Clinical Trial Test Review',
    sysdate - 62,
    'P3',
    'ON HOLD'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    4,
    10,
    'Ergonomic Furniture Upgrade',
    sysdate - 40,
    'P1',
    'CANCELLED'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    5,
    5,
    'Angular Library Upgrade',
    sysdate - 45,
    'P2',
    'OPEN'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    6,
    6,
    'Security Development',
    sysdate - 52,
    'P3',
    'COMPLETE'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    7,
    5,
    'Shipping Process Review',
    sysdate - 23,
    'P1',
    'ON HOLD'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    8,
    1,
    'Metric Monitoring UX Review',
    sysdate - 47,
    'P2',
    'CANCELLED'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    9,
    2,
    'Agile Scrum Training',
    sysdate - 72,
    'P3',
    'OPEN'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    10,
    6,
    'GUID Based Public IDs',
    sysdate - 12,
    'P1',
    'COMPLETE'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    11,
    7,
    'Elastic Rightsize Automation',
    sysdate - 55,
    'P2',
    'ON HOLD'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    12,
    10,
    'Claim Fraud Management',
    sysdate - 62,
    'P3',
    'CANCELLED'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    13,
    1,
    'Global Currency Migration',
    sysdate - 49,
    'P1',
    'OPEN'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    14,
    2,
    'Application Resiliency Harness',
    sysdate - 36,
    'P2',
    'COMPLETE'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    15,
    10,
    'Inventory Email Alert System',
    sysdate - 59,
    'P3',
    'ON HOLD'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    16,
    9,
    'CVE H12 System',
    sysdate - 45,
    'P1',
    'CANCELLED'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    17,
    3,
    'Parallel merge',
    sysdate - 85,
    'P2',
    'OPEN'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    18,
    2,
    'Onboard module',
    sysdate - 50,
    'P3',
    'COMPLETE'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    19,
    8,
    'Open Source Review',
    sysdate - 28,
    'P1',
    'ON HOLD'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    20,
    8,
    'Marketing to Millennial',
    sysdate - 44,
    'P2',
    'CANCELLED'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    21,
    1,
    'NetSuite Module Rollout',
    sysdate - 27,
    'P3',
    'OPEN'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    22,
    7,
    'Angular Smart Table',
    sysdate - 68,
    'P1',
    'COMPLETE'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    23,
    8,
    'Airline Upgrade',
    sysdate - 81,
    'P2',
    'ON HOLD'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    24,
    10,
    'Digital Branding',
    sysdate - 71,
    'P3',
    'CANCELLED'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    25,
    10,
    'APAC Region Dashboard',
    sysdate - 6,
    'P1',
    'OPEN'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    26,
    9,
    'Employee Evaluation Reviews',
    sysdate - 34,
    'P2',
    'COMPLETE'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    27,
    2,
    'Business Intelligence Module',
    sysdate - 44,
    'P3',
    'ON HOLD'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    28,
    6,
    'Visual Metric Portal',
    sysdate - 50,
    'P1',
    'CANCELLED'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    29,
    1,
    'Addison Road Upgrade',
    sysdate - 85,
    'P2',
    'OPEN'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    30,
    9,
    'Search Engine Optimization',
    sysdate - 19,
    'P3',
    'COMPLETE'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    31,
    3,
    'Physical Security Analysis',
    sysdate - 58,
    'P1',
    'ON HOLD'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    32,
    7,
    'Speech Configuration',
    sysdate - 74,
    'P2',
    'CANCELLED'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    33,
    2,
    'Mach 5 Speed Test',
    sysdate - 54,
    'P3',
    'OPEN'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    34,
    4,
    'Optimized Modernization',
    sysdate - 99,
    'P1',
    'COMPLETE'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    35,
    1,
    'Responsive Interface Deployment',
    sysdate - 10,
    'P2',
    'ON HOLD'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    36,
    6,
    'Mach Practices',
    sysdate - 33,
    'P3',
    'CANCELLED'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    37,
    4,
    'Cloud Training',
    sysdate - 83,
    'P1',
    'OPEN'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    38,
    10,
    'Event Registration Application',
    sysdate - 41,
    'P2',
    'COMPLETE'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    39,
    9,
    'Data Privacy Review',
    sysdate - 89,
    'P3',
    'ON HOLD'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    40,
    10,
    'Inventory Optimization',
    sysdate - 79,
    'P1',
    'CANCELLED'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    41,
    8,
    'LOB Productivity Study',
    sysdate - 94,
    'P2',
    'OPEN'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    42,
    10,
    'Reduce Development Cost',
    sysdate - 91,
    'P3',
    'COMPLETE'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    43,
    10,
    'Fax System Retirement',
    sysdate - 85,
    'P1',
    'ON HOLD'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    44,
    2,
    'Entrepreneur Program Review',
    sysdate - 6,
    'P2',
    'CANCELLED'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    45,
    2,
    'System Instrumentation',
    sysdate - 83,
    'P3',
    'OPEN'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    46,
    3,
    'Platform Management',
    sysdate - 86,
    'P1',
    'COMPLETE'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    47,
    3,
    'Tax Automation',
    sysdate - 30,
    'P2',
    'ON HOLD'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    48,
    10,
    'Support Ticket Resolution Time Reduction',
    sysdate - 52,
    'P3',
    'CANCELLED'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    49,
    1,
    'Continuous Testing',
    sysdate - 14,
    'P1',
    'OPEN'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    50,
    8,
    'Tablet Automation Rollout',
    sysdate - 11,
    'P2',
    'COMPLETE'
);

commit;
 
-- Generated by Quick SQL Sunday April 26, 2020  11:21:47
 
/*
#apex: true, auditcols: true 
assignees /insert 10
  full_name /nn
  email
  phone_number
  todos /insert 50 
    name vc255 /nn 
    due_date date
    priority vc50 /check P1, P2, P3
    status vc50 /check OPEN, COMPLETE, ON HOLD, CANCELLED

# settings = { PK: "IDENTITY", auditCols: true, drop: true, language: "EN", APEX: true }
*/
